-- Create the User table
CREATE TABLE "User" (
    userID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    verified NUMBER(1) DEFAULT 0, -- 0 = not verified, 1 = verified
    verificationToken VARCHAR2(255),
    resetToken VARCHAR2(255)
);

-- Create the Recipe table (User table must exist first)
CREATE TABLE Recipe (
    recipeID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    title VARCHAR2(100) NOT NULL,
    ingredients CLOB,
    instructions CLOB,
    userID NUMBER,
    FOREIGN KEY (userID) REFERENCES "User"(userID)
);

-- Create the Media table (Recipe table must exist first)
CREATE TABLE Media (
    mediaID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    filePath VARCHAR2(255),
    mediaType VARCHAR2(50),
    recipeID NUMBER,
    FOREIGN KEY (recipeID) REFERENCES Recipe(recipeID)
);
